# github.yml 
name: building_docker_github
description: ''

inputs:

  # Required 
  auth_token:
    description: "Authentication token for access."
    required: true

  dockerfile_context:
    description: "Build context directory."
    required: false
    default: './'

  dockerfile_path:
    description: "Path to the Dockerfile."
    required: false
    default: './Dockerfile'

  # Optional
  docker_option_buildkit:
    description: "Enable Docker BuildKit."
    required: false
    default: 'true'

  docker_build_arguments:
    description: "Custom build arguments."
    required: false

  docker_build_tag:
    description: "Tag for the Docker image."
    required: false

runs:
  using: composite 
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
             
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: 'ghcr.io' 
        username: ${{ github.actor }}
        password: ${{ inputs.auth_token }}

    - name: Build and push Docker image
      shell: bash
      working-directory: "${{ inputs.dockerfile_context }}"
      env:
        DOCKER_BUILDKIT: 1
      run: |

        # build 
        docker build                                   \
          $(echo ${{ inputs.docker_build_arguments }}) \
          --tag ${{ inputs.docker_build_tag }}         \
          --file ${{ inputs.dockerfile_path }}         \
          .

        # push
        docker push ${{ inputs.docker_build_tag }} 
