#!/usr/bin/env ansible-playbook

#####################################
# Configuration: 
#####################################

- name: Extra Configuration
  shell: "{{ item }}"
  loop: 
    "{{ 
      configuration | 
      flatten | 
      list 
    }}"
  when: configuration | list | length > 0
