#!/usr/bin/env ansible-playbook

######################################
# BASE 
######################################

- name: Gather system facts
  setup:

- name: Check for existing installation
  command: "{{ check_command }}"
  register: check_package
  changed_when: false
  failed_when: false

- name: Installation
  block:

    - name: Prerequisites
      package:
        name:
          - curl
          - gnupg
          - software-properties-common
          - apt-transport-https
        state: present

    - name: Download GPG key
      get_url:
        url: "{{ gpg_key_url }}"
        dest: "/usr/share/keyrings/{{ package_name }}-keyring.asc"
        mode: '0644'
        force: true

    - name: Add APT repository for {{ package_name }}
      copy:
        content: "deb [signed-by=/usr/share/keyrings/{{ package_name }}-keyring.asc] {{ repo_url }}"
        dest: "/etc/apt/sources.list.d/{{ package_name }}.list"
        mode: '0644'

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install {{ package_name }}
      package:
        name: "{{ package_name }}"
        state: present

  when: check_package != 0
