#!/usr/bin/env ansible-playbook

#######################################
# BASE 
#######################################

#- name: Presence
#  command: nvidia-smi 
#  register: check_nvidia
#  changed_when: false
#  failed_when: false

- name: Installation 
  block:
    - name: Get the latest NVIDIA download URL
      command: >
        curl -s -X GET https://download.nvidia.com/XFree86/Linux-x86_64/latest.txt
      register: nvidia_url_output
      changed_when: false  # To prevent Ansible from marking this task as changed unnecessarily

    - name: Fetch latest Nvidia driver
      get_url:
        url: "https://download.nvidia.com/XFree86/Linux-x86_64/{{ nvidia_url_output.stdout.split()[1] }}"
        dest: /tmp/nvidia.run
        mode: '0755'
      when: nvidia_url_output.stdout is not none

    - name: Install latest Nvidia driver 
      command: >
        /tmp/nvidia.run \
          --silent \
          --install-compat32-libs \
          --no-kernel-module 
      when: nvidia_url_output.stdout is not none
      register: install_output

    - name: Display installation output
      debug:
        var: install_output.stdout_lines
      when: install_output is defined

        #  when: check_nvidia.rc !=0
