#!/usr/bin/env ansible-playbook

#####################################
# Configuration: 
#####################################

- name: Copy Kubeconfig to user's home directory
  ansible.builtin.copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ ansible_env.HOME }}/.kube/config"
    owner: "{{ ansible_env.USER }}"
    mode: '0644'
