#!/usr/bin/env ansible-playbook

#####################################
# Configuration: 
#####################################

- name: Expose Kubeconfig globaly
  shell: echo KUBECONFIG=/etc/rancher/k3s/k3s.yaml | tee -a /etc/environment
