#!/usr/bin/env ansible-playbook

######################################
# BASE 
#######################################

- name: Gather system facts
  setup:

- name: Presence
  command: /usr/local/bin/k3s --version
  register: check_k3s
  changed_when: false
  failed_when: false

- name: Installing 
  block:
    - name: Prerequisites
      package:
        name:
          - curl 
        state: present

    - name: Execute 
      raw: curl -sfL https://get.k3s.io | sh -s -

  when: check_k3s.rc !=0
