#!/usr/bin/env ansible-playbook

#######################################
# BASE 
#######################################

- name: Gather system facts
  setup:

- name: Presence
  command: kubectl version
  register: check_kubectl
  changed_when: false
  failed_when: false

- name: Installation
  block:

    - name: Prerequisites
      package:
        name:
          - curl
          - gnupg
          - software-properties-common
          - apt-transport-https
        state: present

    - name: Add GPG Key
      get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key
        dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
        mode: '0644'
        force: true

    - name: Add APT repository
      copy:
        content: |
         deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ / 
        dest: /etc/apt/sources.list.d/kubernetes.list
        mode: '0644'

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install package 
      package:
        name: kubectl
        state: present

  when: check_kubectl != 0
