#!/usr/bin/env ansible-playbook

#######################################
# BASE 
#######################################

- name: Installation 
  block:
    - name: Package
      package:
        name:
        - kubernetes-client
        state: present
