apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream
  labels:
    {{- include "stream.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.global.annotations | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "stream.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "stream.labels" . | nindent 8 }}
    spec:
      runtimeClassName: nvidia
      containers:
        - name: stream
          {{- if .Values.stream.command }}
          command:
            {{- range .Values.stream.command }}
            - {{ . | quote }}
            {{- end }}
          {{- end }}
          image: {{ include "stream.imageByParams" (dict "base" .Values.stream) }}
          imagePullPolicy: {{ .Values.stream.image.pullPolicy }}
          resources:
            {{- toYaml .Values.stream.resources | nindent 12 }}
          ports:
            - containerPort: 8080
              name: stream 
              protocol: TCP
            - containerPort: 9090
              name: metrics 
              protocol: TCP
            - containerPort: 9091
              name: supervisor 
              protocol: TCP
          env:
          {{- with .Values.stream.env }}
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          {{- with .Values.stream.nodeSelector }}
          nodeSelector:
          {{ toYaml . | indent 2 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.stream.extraVolumes }}
            {{- range .Values.stream.extraVolumes }}
            - name: {{ .name }}
              mountPath: {{ .volumeMount }} 
            {{- end }}
            {{- end }}
      volumes:
        {{- if .Values.stream.extraVolumes }}
        {{- range .Values.stream.extraVolumes }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .name }}
        {{- end }}
        {{- end }}
